In [24]:
#1  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type
import numpy as np
arr=np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#2 Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
arr1 = np.array([1.5,2.6,3.7], dtype=np.float64)
arr1.dtype is np.float64

False

In [16]:
#3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
a=np.arange(128).reshape((4,4,8))
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31]],

       [[ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]]])

In [ ]:
#4 Convert an existing NumPy array 'arr' of integers to float32 data type.
integer_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.int32)
 
print("Float Array with Int32 Data Type:")
print(float_array)

Float Array with Int32 Data Type:
[1 2 3 4 5]


In [ ]:
#5  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
integer_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.int32)
 
print("Integer Array with Float64 Data Type:")
print(integer_array)
 
print("Float Array with Int32 Data Type:")
print(float_array)

Integer Array with Float64 Data Type:
[1. 2. 3. 4. 5.]
Float Array with Int32 Data Type:
[1 2 3 4 5]


In [ ]:
#6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
#type.
arr= np.array([[10,11,12,13],[2,3,4,5],[56,76,56,45]])
arr

array([[10, 11, 12, 13],
       [ 2,  3,  4,  5],
       [56, 76, 56, 45]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
#7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
x= np.array([[2,5,6]])
x.ndim

2

In [ ]:
y= np.zeros((2,4,6,7,3))
y.ndim

5

In [ ]:
#8  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#size in bytes.
x = np.array([[100, 20, 34],
              [300, 400, 600]])
 
print("Size of the array:",x.size)
 
print("Memory size of one array element in bytes:", x.itemsize)
 
# memory size of numpy array
print("Memory size of numpy array in bytes:", x.size* x.itemsize)

Size of the array: 6
Memory size of one array element in bytes: 4
Memory size of numpy array in bytes: 24


In [ ]:
#9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
x = np.reshape(np.arange(2*3*4), (2,3,4))
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x.strides

(48, 16, 4)

In [ ]:
#10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
#and strides of the array
x = np.reshape(np.arange(3*3*4), (3,3,4))
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [ ]:
x.strides

(48, 16, 4)

In [ ]:
x[2,2,2]

34

In [ ]:
offset=sum(x.strides * np.array((1,1,1)))
offset/x.itemsize

17.0

In [ ]:
#11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
#zeros with `n` elements.
#creating 3D array
arr = np.zeros((3, 4, 5))
 
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
#12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.
def create_matrix(row, col):
    ''' create a 2D matrix by consecutive numbers - starting 1 - or change to whatever number in code

    '''

    matrix = [[ j + (col *i) for j in range(1, col+1)] # 1
                             for i in range(row)]

    return matrix
print(create_matrix(4,5))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [ ]:
#13  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step.

np.arange(start=5, stop=50, step=2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [ ]:
#14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
np.linspace(start=3, stop=20)

array([ 3.        ,  3.34693878,  3.69387755,  4.04081633,  4.3877551 ,
        4.73469388,  5.08163265,  5.42857143,  5.7755102 ,  6.12244898,
        6.46938776,  6.81632653,  7.16326531,  7.51020408,  7.85714286,
        8.20408163,  8.55102041,  8.89795918,  9.24489796,  9.59183673,
        9.93877551, 10.28571429, 10.63265306, 10.97959184, 11.32653061,
       11.67346939, 12.02040816, 12.36734694, 12.71428571, 13.06122449,
       13.40816327, 13.75510204, 14.10204082, 14.44897959, 14.79591837,
       15.14285714, 15.48979592, 15.83673469, 16.18367347, 16.53061224,
       16.87755102, 17.2244898 , 17.57142857, 17.91836735, 18.26530612,
       18.6122449 , 18.95918367, 19.30612245, 19.65306122, 20.        ])

In [ ]:
#15  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye.
np.eye(3*3)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#16 Write a function that takes a Python list and converts it into a NumPy array.
list=[11,12,13,10,16,16,17]
arr= np.array(list)
arr
print("List:", list)
print("Array:", arr)

List: [11, 12, 13, 10, 16, 16, 17]
Array: [11 12 13 10 16 16 17]


In [ ]:
#17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
x=np.array([2,3,4,5,6])
y=np.array([10,11,12,13,14])
z = np.empty(2, dtype=object)
z[:] = [x,y]
print(id(x))
print(id(z[0]))

1408501824560
1408501824560


In [ ]:
#18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.
arr1=np.array([3,4,5,6,7,8])
arr2=np.array([10,11,12,13,14,15])
np.concatenate((arr1,arr2),axis=0)

array([ 3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15])

In [ ]:
#19  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`
arr1=np.array([[3,4,5,6,7,8,9,10]])
arr2=np.array([[10,11,12,13,14,15]])
np.hstack((arr1,arr2))

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 10, 11, 12, 13, 14, 15]])

In [ ]:
#20 Write a function that vertically stacks multiple NumPy arrays given as a list.
arr1=np.array([[3,4,5,6,7,8]])
arr2=np.array([[10,11,12,13,14,15]])
arr3=np.array([[1,3,5,9,0,6]])
np.vstack((arr1,arr2,arr3))

array([[ 3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15],
       [ 1,  3,  5,  9,  0,  6]])

In [ ]:
#21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1  (inclusive)
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#23  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
#1000 (inclusive).
print("B\n", np.logspace(1,1000, num=5, base = 5))
 
# base = 5
print("B\n", np.logspace(1,1000, num=5))
 
# base = 5, dtype = int
print("B\n", np.logspace(1,1000, num=5, dtype = int))

B
 [5.00000000e+000 1.84811328e+175             inf             inf
             inf]
B
 [1.00000000e+001 5.62341325e+250             inf             inf
             inf]
B
 [         10 -2147483648 -2147483648 -2147483648 -2147483648]


C:\Users\dyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)
C:\Users\dyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\function_base.py:299: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y).astype(dtype, copy=False)
C:\Users\dyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\function_base.py:299: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


In [ ]:
#24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100.
import pandas as pd
data = np.random.randint(1, 100, size=(5, 3))
df = pd.DataFrame(data, columns=['random_no_1',
                                 'random_no_2',
                                 'random_no_3'])
print(df)

   random_no_1  random_no_2  random_no_3
0           11           78           73
1           14            4           56
2           95           37           97
3            3            7           69
4           25            1           19


In [ ]:
#25  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame.
df = pd.DataFrame({"A": [1, 2, -3, 4, -5, 6], 
                   "B": [3, -5, -6, 7, 3, -2], 
                   "C": [-4, 5, 6, -7, 5, 4], 
                   "D": [34, 5, 32, -3, -56, -54]}) 
print("original array:",)
df

original array:


A  B  C   D
0  1  3 -4  34
1  2 -5  5   5
2 -3 -6  6  32
3  4  7 -7  -3
4 -5  3  5 -56
5  6 -2  4 -54

In [ ]:
# checking the element is < 0 
df[df < 0] = 0
print("New Array :") 
df 

New Array :


A  B  C   D
0  1  3  0  34
1  2  0  5   5
2  0  0  6  32
3  4  7  0   0
4  0  3  5   0
5  6  0  4   0

In [ ]:
#26 Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[3]

40

In [ ]:
#27 Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1]+ arr_2d[2])

[11 13 15]


In [ ]:
#28 Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
mask= arr>5
mask
#Boolean indexing
filtered_arr= arr[mask]
print(filtered_arr)


[ 8 10  7]


In [ ]:
#29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])

[3 4 5 6]


In [ ]:
#30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_matrix= arr_2d[0:2,1:3]
print(sub_matrix)

[[2 3]
 [5 6]]


In [ ]:
#31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array.
input = np.array([[1,2],[3,4]])
input

array([[1, 2],
       [3, 4]])

In [ ]:
indices = np.array([[0],[1]])
indices

array([[0],
       [1]])

In [ ]:
res = input[np.arange(input.shape[0])[:, None], indices]
print(res)

[[1]
 [4]]


In [ ]:
#32 Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#boolean indexing. 
arr = np.array([3, 8, 12, 10, 15, 7])
mask= arr>10
mask
#Boolean indexing
filtered_arr= arr[mask]
print(filtered_arr)

[12 15]


In [ ]:
#33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#separate arrays for each dimension.
import numpy as np
data = np.arange(125).reshape(5,5,5)
data


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [ ]:
indices = np.array(((0, 0, 0), (4, 4, 4), (0, 0, 4)), dtype=int)
data[tuple(indices.T)]

array([  0, 124,   4])

In [ ]:
#34 Write a NumPy function that returns elements from an array where both two conditions are satisfied
#using boolean indexing.
data=np.array([10,2,12,11,14,13,15,17,16,18,9])
mask= data>=10
mask

#Boolean indexing
filtered_data= data[mask]
print(filtered_data)

[10 12 11 14 13 15 17 16 18]


In [ ]:
#35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays. 
A = np.array([[1,2],[3,4]])
idx = np.array([[0],[1]])

res = A[np.arange(A.shape[0])[:, None], idx]

print(res)


[[1]
 [4]]


In [ ]:
#36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([3,5,6, 8, 12, 10,11, 15, 7])
arr.reshape(3,3)
arr+5

array([ 8, 10, 11, 13, 17, 15, 16, 20, 12])

In [ ]:
#37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting.

arr1=np.array([12,23,34])
arr2= np.array([2,12,3,4,5,6,7,8,9,10,12,13])
arr2_reshape= arr2.reshape(3,4)
arr1_reshape=arr1.reshape(3,1)
arr1_reshape*arr2_reshape

array([[ 24, 144,  36,  48],
       [115, 138, 161, 184],
       [306, 340, 408, 442]])

In [ ]:
#38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
#NumPy broadcasting.
arr1=np.array([12,23,34,13])
arr2= np.array([2,12,3,4,5,6,7,8,9,10,12,13])
arr2_reshape= arr2.reshape(4,3)
arr1_reshape=arr1.reshape(4,1)
arr1_reshape+arr2_reshape

array([[14, 24, 15],
       [27, 28, 29],
       [41, 42, 43],
       [23, 25, 26]])

In [ ]:
#39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1=np.array([12,23,34])
arr2= np.array([2,12,23])
arr2_reshape= arr2.reshape(1,3)
arr1_reshape=arr1.reshape(3,1)
arr1_reshape+arr2_reshape

array([[14, 24, 35],
       [25, 35, 46],
       [36, 46, 57]])

In [ ]:
#40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#broadcasting. Handle the shape incompatibility.
arr1=np.array([12,23,34,13,16,20])
arr2= np.array([2,10,12,23])
arr2_reshape= arr2.reshape(2,2)
arr1_reshape=arr1.reshape(2,3)
#arr1_reshape*arr2_reshape
Result = np.multiply.outer(arr1,arr2)
Result

array([[ 24, 120, 144, 276],
       [ 46, 230, 276, 529],
       [ 68, 340, 408, 782],
       [ 26, 130, 156, 299],
       [ 32, 160, 192, 368],
       [ 40, 200, 240, 460]])

In [ ]:
#41 Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.mean(arr.reshape((3, 2)), axis=1)
print(result)


[1.5 3.5 5.5]


In [ ]:
#42 . Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,1)


array([3, 6])

In [ ]:
#43 For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,0)

array([4, 5, 6])

In [ ]:
#44  For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr,axis=1))

[ 6 15]


In [ ]:
#45  In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(arr[arr % 2 == 0])

[2 4 6]


In [ ]:
#46  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
original_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#47 Create a function that takes a matrix as input and returns the flattened array
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
input_matrix.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
#48 Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1,array2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#49 Create a function that splits an array into multiple sub-arrays along a specified axis
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(original_array,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [35]:
# 50 Write a function that inserts and then deletes elements from a given array at specified indices.
score = [43,45,99,76] 
#inserting a new score at third position 
score.insert(2, 500) 
#printing new list 
print(score)
score.remove(500)
print(score)

[43, 45, 500, 99, 76]
[43, 45, 99, 76]


In [415]:
#51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#Perform element-wise addition between `arr1` and `arr2`.
arr1=np.array([12,11,34,23,56,7,8,9,10,1])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
x=arr1.reshape(10,1)
y=arr2.reshape(10,1)
z=np.add(arr1,arr2)
print(z)


[13 13 37 27 61 13 15 17 19 11]


In [416]:
#52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
#from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1=np.array([12,11,34,23,56,7,8,9,10,1])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
x=arr1.reshape(10,1)
y=arr2.reshape(1,10)
z=np.subtract(arr1,arr2)
print(z)

[11  9 31 19 51  1  1  1  1 -9]


In [417]:
#53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2
arr1= np.array([23,12,56,45,68])
arr2= np.array([1,2,3,4,5])
arr1*arr2

array([ 23,  24, 168, 180, 340])

In [429]:
#54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#to 5. Perform element-wise division of `arr1` by `arr2`.
arr=np.array([2,3,4,5,6,7,8,9,10])
arr=arr[arr%2 == 0] 
arr1=print(arr)
arr1=np.array([2,4,6,8,10])
arr2=np.array([1,2,3,4,5])

print(arr1/arr2)


[ 2  4  6  8 10]
[2. 2. 2. 2. 2.]


In [430]:
#55 Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])
np.power(arr1,arr2)

array([ 1, 16, 27, 16,  5])

In [441]:
#56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count = np.char.count(arr, sub ='hello') 
print(count)

[1 0 1 0 1]


In [443]:
#57 Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print ("input array : ", arr) 
  
out_arr = np.char.upper(arr) 
print ("output uppercased array :", out_arr) 

input array :  ['Hello' 'World' 'OpenAI' 'GPT']
output uppercased array : ['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [450]:
#58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
s1="apple"
s2= "mango"
arr1=np.char.replace(arr,"apple","mango")
print(arr1)

['mango' 'banana' 'grape' 'pinemango']


In [457]:
#59 Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result=np.char.add(arr1 , arr2)
result

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [458]:
#60 Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(max(arr, key=len))

pineapple


In [487]:
#61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#standard deviation of the dataset using NumPy's functions.
import random
res = random.sample(range(1, 1000), 100)
res
print("Dataset:",res)
x= np.mean(res)
print("mean of dataset:",x)
y=np.median(res)
print("median:",y)
z=np.var(res)
print("varianve:", z)
z1=np.std(res)
print("standard deviation:", res)

Dataset: [117, 699, 516, 529, 495, 45, 635, 373, 864, 82, 877, 119, 906, 444, 611, 22, 812, 913, 412, 893, 77, 156, 139, 947, 713, 862, 335, 326, 438, 474, 369, 912, 764, 202, 481, 350, 750, 671, 761, 150, 524, 76, 776, 308, 234, 446, 594, 828, 133, 320, 905, 25, 44, 32, 972, 632, 504, 739, 486, 274, 394, 39, 935, 190, 736, 595, 576, 451, 678, 817, 839, 867, 177, 114, 410, 176, 91, 349, 557, 715, 890, 86, 262, 626, 264, 587, 160, 400, 954, 706, 472, 416, 708, 397, 965, 6, 882, 606, 974, 897]
mean of dataset: 500.57
median: 490.5
varianve: 86589.8051
standard deviation: [117, 699, 516, 529, 495, 45, 635, 373, 864, 82, 877, 119, 906, 444, 611, 22, 812, 913, 412, 893, 77, 156, 139, 947, 713, 862, 335, 326, 438, 474, 369, 912, 764, 202, 481, 350, 750, 671, 761, 150, 524, 76, 776, 308, 234, 446, 594, 828, 133, 320, 905, 25, 44, 32, 972, 632, 504, 739, 486, 274, 394, 39, 935, 190, 736, 595, 576, 451, 678, 817, 839, 867, 177, 114, 410, 176, 91, 349, 557, 715, 890, 86, 262, 626, 264, 587, 160,

In [499]:

#62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr=random.sample(range(1,100),50)
arr
x=np.sort(arr)
print("sort num:", x)
y = (25/100) * (50 - 1) + 1
print("25 percentile:", y)
z= (75/100) * (50-1)+1
print("75 percentile:", z)

sort num: [ 2  4  5  6  7  9 10 14 17 20 21 23 27 30 32 33 35 36 44 45 48 49 50 51
 52 54 56 57 60 63 65 66 70 71 72 73 75 76 79 80 81 86 88 90 91 93 95 96
 98 99]
25 percentile: 13.25
75 percentile: 37.75


In [509]:
#63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#arrays using NumPy's `corrcoef` function.


rng= np.random.default_rng(seed=42)
xarr = data.random((3, 3))
print(xarr)
R1 = np.corrcoef(xarr)
R1
yarr = rng.random((3, 3))
print(yarr)
R3 = np.corrcoef(xarr, yarr, rowvar=False)
print(R3)

[[0.80476436 0.38747838 0.2883281 ]
 [0.6824955  0.13975248 0.1999082 ]
 [0.00736227 0.78692438 0.66485086]]
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
[[ 1.         -0.86184364 -0.94832919 -0.2220392  -0.78730963  0.96361399]
 [-0.86184364  1.          0.97823179  0.68587693  0.99123994 -0.96605107]
 [-0.94832919  0.97823179  1.          0.51993414  0.94225517 -0.99863367]
 [-0.2220392   0.68587693  0.51993414  1.          0.77598074 -0.47458546]
 [-0.78730963  0.99123994  0.94225517  0.77598074  1.         -0.92346708]
 [ 0.96361399 -0.96605107 -0.99863367 -0.47458546 -0.92346708  1.        ]]


In [512]:
#64 Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.array([2,3,5,19,18])
print(arr1)
arr2=np.array([10,11,12,13,14])
print(arr2)
np.dot(arr1,arr2)

[ 2  3  5 19 18]
[10 11 12 13 14]


612

In [530]:
#65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#percentiles along with the first and third quartiles.

arr=random.sample(range(10,1000),50)
arr
arr1= np.sort(arr)
arr1
median= (209+992)/2
print("median of 10,50:", median)
y = (90/100) * (50 - 1) + 1
print("90 percentile:", y)


median of 10,50: 600.5
90 percentile: 45.1


In [531]:
#66 Create a NumPy array of integers and find the index of a specific element.
a = np.array([1, 2, 3, 4, 8, 6, 7, 3, 9, 10])
 
# display index value of 3
print("All index value of 3 is: ", np.where(a == 3)[0])
 
print("First index value of 3 is: ",np.where(a==3)[0][0])

All index value of 3 is:  [2 7]
First index value of 3 is:  2


In [534]:
#67 Generate a random NumPy array and sort it in ascending order.
arr= random.sample(range(1,100),20)
print(arr)
np.sort(arr)

[53, 85, 54, 40, 59, 30, 7, 39, 22, 82, 55, 23, 24, 1, 73, 52, 79, 61, 94, 98]


array([ 1,  7, 22, 23, 24, 30, 39, 40, 52, 53, 54, 55, 59, 61, 73, 79, 82,
       85, 94, 98])

In [547]:
#68  Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filter_arr=[]
#axis = 0
#print(np.take(arr, filtered_arr, axis))
for element in arr:
  # if the element is higher than 2, set the value to True, otherwise False:
  if element > 20:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True]
[25 42 30]


In [548]:
#69  Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
mask=(arr%3==0)
print(arr[mask])

[12 15]


In [554]:
#70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filter_arr=[]
for element in arr:
  # if the element is higher than 2, set the value to True, otherwise False:
  if element >= 20 and element<=40:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, True, True, False]
[20 30 40]


In [41]:
#71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
dt = np.dtype('i2')
dt.byteorder
'='
# endian is not relevant for 8 bit numbers
np.dtype('i1').byteorder
'|'
# or ASCII strings
np.dtype('S2').byteorder
'|'
# Even if specific code is given, and it is native
# '=' is the byteorder
import sys
sys_is_le = sys.byteorder == 'little'
native_code = '<' if sys_is_le else '>'
swapped_code = '>' if sys_is_le else '<'
dt = np.dtype(native_code + 'i2')
dt.byteorder
'='
# Swapped code shows up as itself
dt = np.dtype(swapped_code + 'i2')
dt.byteorder == swapped_code

True

In [556]:
#72  For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
   
print(a.byteswap(True))

[ 16777216  33554432  50331648  67108864 134217728 100663296 117440512
  50331648 150994944 167772160]


In [560]:
#73 For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()
from io import BytesIO
x = np.array([1, 2, 3], dtype=np.int32)
y = x.byteswap(False)
z = x.newbyteorder('S')
for array in [x, y, z]:

    b1 = BytesIO()
    b1.write(array.data)
    b1.seek(0)
    print(b1.read())


b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03'
b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'


In [562]:
#75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
#attribute `byteorder
arr = np.array([1, 2, 3], dtype=np.int32)
def swap32(x):
    y = bytearray(x)
a = np.array(y, dtype=np.uint32)
bytes(a.byteswap())
brr = bytes(arr)
brr

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

In [563]:
#76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
org_array = np.array([1.54, 2.99, 3.42, 4.87, 6.94,
                      8.21, 7.65, 10.50, 77.5])
 
print("Original array: ")
 
# printing the Numpy array
print(org_array)
 
# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)
 
print("\nCopied array: ")
 
# printing the copied Numpy array
print(copy_array)

Original array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]

Copied array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]


In [571]:
#77  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
from numpy import reshape
x = range(9)
x = reshape(x,(3,3))
print(x)
x[2,0]=100
x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  0,   1,   2],
       [  3,   4,   5],
       [100,   7,   8]])

In [10]:
#78  Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
import numpy as np
arr_a = np.arange(1,13).reshape(( 4, 3))
print(arr_a)
a=view_b=slice(0,2)
a
b=print(arr_a[view_b])
b
#b=np.array([5,5,5 ])
c=np.array([[5,5,5],[5,5,5],[5,5,5],[5,5,5]])
print(c)
np.add(arr_a,c)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [609]:
#79 Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#reflects changes in the original `orig_array`.
orig_array= np.arange(1,9).reshape(( 2,4))
print(orig_array)
reshaped_view= np.reshape((orig_array),(4,2))
reshaped_view

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
#80 . Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data= np.arange(1,13).reshape((3,4))
print(data)
data_copy=[]
for element in data:
  # if the element is higher than 2, set the value to True, otherwise False:
  if element > 5:
    data_copy.append(True)
  else:
    data_copy.append(False)

newarr = data_copy[data]

print(data_copy)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [642]:
#81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#operations between them.
A=np.matrix([10,11,12,13,14,45,13])
print(A)
B=np.matrix([99,89,67,68,46,56,34])
print(B)
print(A+B)
print(A-B)

[[10 11 12 13 14 45 13]]
[[99 89 67 68 46 56 34]]
[[109 100  79  81  60 101  47]]
[[-89 -78 -55 -55 -32 -11 -21]]


In [670]:
#82 Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

# create first matrix 
C = np.matrix([[3,4,5],[2,3,4],[3,3,6]])
C
# create second matrix 
D = np.matrix([[3,4,2],[7,8,9],[12,10,4]])
D
# display  
print(C) 
  
print(D)
print(C*D)

[[3 4 5]
 [2 3 4]
 [3 3 6]]
[[ 3  4  2]
 [ 7  8  9]
 [12 10  4]]
[[ 97  94  62]
 [ 75  72  47]
 [102  96  57]]


In [10]:
#83 Create a matrix `E` and find its transpose.
E = np.matrix([[3,4,5],[2,3,4],[3,3,6]])
print(E)
E.T

[[3 4 5]
 [2 3 4]
 [3 3 6]]


matrix([[3, 2, 3],
        [4, 3, 3],
        [5, 4, 6]])

In [5]:
#84  Generate a square matrix `F` and compute its determinant.
from math import sqrt
import numpy as np
def square_matrix(*elements):
    size = sqrt(len(elements))
    if size.is_integer():
      return np.array(elements).reshape(int(size), int(size))
    else:
      raise RuntimeError("Number of elements is not sufficient to make a square matrix")


print(square_matrix(1, 2, 3, 4, 5, 6, 7, 8, 9))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#85  Create a square matrix `G` and find its inverse.
from math import sqrt
import numpy as np
def square_matrix(*elements):
    size = sqrt(len(elements))
    if size.is_integer():
      return np.array(elements).reshape(int(size), int(size))
    else:
      raise RuntimeError("Number of elements is not sufficient to make a square matrix")


print(square_matrix(10, 21, 32, 40, 35, 56, 17, 28, 89))
print(1/square_matrix(10, 21, 32, 40, 35, 56, 17, 28, 89))

[[10 21 32]
 [40 35 56]
 [17 28 89]]
[[0.1        0.04761905 0.03125   ]
 [0.025      0.02857143 0.01785714]
 [0.05882353 0.03571429 0.01123596]]
